import React from 'react';

export default function About() {
  return (
    <div>
      <h1>About Me</h1>
      <img className="profile-picture" src="/Headshot.jpg" alt="picture" />
      <p>I was born and raised in Caracas, Venezuela. Did most of my studies there with the exception of 1 year of high school when I went to Connecticut to improve my English skills and this is where I ended up meeting my future wife. In Venezuela, I developed an unmatchable passion for fishing (The La Guaira Banks is one of the top spots for fishing in the world!). As a family, we always chose the dinner table as our favorite place to share, and this flourished an interest in cooking as well as entertaining. I started working at Toyota of Venezuela as a marketing analyst and enjoyed it tremendously. I worked in the automotive industry for about 8 years, out of which I spent 3 and a half in Japan working for Toyota Motor Corporation. I decided to move to Denver in 2014 when I had an opportunity to help the Stanley Brothers with their hemp company. Worked with Hemp and CBD for 5 years and then the pandemic hit. After that, I worked at a wine shop for a little bit to pursue my passion for wines.</p>

      <p>While studying Industrial Engineering in Caracas, I spent 4 months in Cartagena, Colombia learning about the shrimping business so that we could bring the know-how back to my friend's land in the west side of Venezuela, in order to develop a shrimp farm. After this, I went to Nagoya, Japan for an extended business training for a year and a half at the headquarters of Toyota Motor Corporation. Came back to Venezuela where I worked at the Toyota of Venezuela's Marketing and Sales department until I was sent back to Japan (this time to Tokyo, as the offices for Latin American had moved from Nagoya back to Tokyo) as an Inter-Company Trainee for 2 years. While in Tokyo, there was an opportunity to help some brothers who had started a Hemp company in Colorado and I quit everything and moved to Denver in mid-2014. I worked for five years in the emerging cannabis industry, specifically in cannabidiol (CBD), expanding and developing our business outside of the U.S. as part of our risk management strategy. Currently, I am working as an advisor to Blue Jay Capital in developing a large hotel with private residences for a major brand in the hospitality industry. Worked for a few months at a wine shop in Cherry Creek where I wanted to pursue my passion for wines. Here I learned a lot in a few months but I also learned how humbling blind tasting can be, and after realizing I would have to dedicate years to achieve the level I was striving for, Had to move on as I wasn't willing to invest years of weekend work away from my 3-year-old son. This is when I thought it would be a good idea to register at the University of Denver's Full Stack Bootcamp, which is culminating in mid-December.</p>

      <p>I live a stone's throw away from the University of Denver, where I share my house with my wife, our 4-year-old son, and our 3 dogs. As I mentioned before, my real passion is fishing, but since moving to Colorado, I've developed a liking for hunting (anything I can eat!), especially if I can take my dogs with me. My wife and I love to play golf in our spare time and when possible, we love to travel to any place we haven't been before!</p>
    </div>
  );
}
